### ISSUE TITLE
Comments to blog

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#1]
Hello,

Thanks for the work you've put into this module.

Please advise if readers of blog posts can comment, like, vote up etc?

Regards,

Adam

**Comment by dbd5** [comment]
No

**Comment by aaiyo** [comment]
I think it would be better to create another module only for messages, so it can be used at any pages that needed to be commented, not only blog, like forum or product details for examples. I've plan to create that one, still wait for some plenty time :) Anyway thank for the advice.

**Comment by dbd5** [comment]
You are welcome Bro!

A
