### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#14]
Hi @aaiyo ,

Of recent I started getting the error below, I have not changed anything and I see that this project has not changed. I have also logged this issue @ https://github.com/fxpio/composer-asset-plugin/issues/234.
Any suggestions what I can do to resolve?

Regards,

Adam

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for amilna/yii2-blog dev-master -> satisfiable by amilna/yii2-blog[dev-master].
    - amilna/yii2-blog dev-master requires iutbay/yii2-kcfinder dev-master -> satisfiable by iutbay/yii2-kcfinder[dev-master].
    - iutbay/yii2-kcfinder dev-master requires iutbay/yii2-fontawesome dev-master -> satisfiable by iutbay/yii2-fontawesome[dev-master].
    - iutbay/yii2-kcfinder dev-master requires iutbay/yii2-fontawesome dev-master -> satisfiable by iutbay/yii2-fontawesome[dev-master].
    - Conclusion: don't install iutbay/yii2-fontawesome dev-master

**Comment by sherinjose** [comment]
Facing the same issue. Couldn't install

**Comment by 4cc355-d3n13d** [comment]
+1

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for amilna/yii2-blog dev-master -> satisfiable by amilna/yii2-blog[dev-master].
    - amilna/yii2-blog dev-master requires iutbay/yii2-kcfinder dev-master -> satisfiable by iutbay/yii2-kcfinder[dev-master].
    - iutbay/yii2-kcfinder dev-master requires iutbay/yii2-fontawesome dev-master -> satisfiable by iutbay/yii2-fontawesome[dev-master].
    - iutbay/yii2-kcfinder dev-master requires iutbay/yii2-fontawesome dev-master -> satisfiable by iutbay/yii2-fontawesome[dev-master].
    - Conclusion: don't install iutbay/yii2-fontawesome dev-master

**Comment by aaiyo** [comment]
i'm sorry for my late respon guys, i don't know why it didn't work, but then a change the require repo to "iutbay/yii2-fontawesome": "*" (also in https://github.com/aaiyo/yii2-kcfinder"), now it is working.
