### ISSUE TITLE
Missing files index / upload tool

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#2]
Hello,

Not sure if I've done anything wrong but the link "Manage files" (Manage files that available to be downloaded by users) leads to an empty page. I was under the impression that there will be a file index and an upload tool?

Please advise, thanks

Adam

**Comment by aaiyo** [comment]
Thank your for the question, and you're right the link should be goes to /blog/file/admin

**Comment by dbd5** [comment]
Link confirmed working, thanks

Adam
