### ISSUE TITLE
Error to view Category

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#3]
Hello,

I have installed this module according to the instructions and proceeded to test as follows
1. Create a Category -> Testing
2. Create a single post and select Category 'Testing'

However, when you display the posts and select view more from the post and then click Categories, the following error is displayed: 

Database Exception – yii\db\Exception

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION trntv.array_agg does not exist
The SQL being executed was: SELECT array_agg(`blog_post`.id) FROM `blog_post` LEFT JOIN `blog_cat_pos` `cp` ON `blog_post`.id = cp.post_id LEFT JOIN `blog_category` `c` ON cp.category_id = c.id WHERE (`blog_post`.isdel=0) AND (lower(c.title) = 'testing')
Error Info: Array
(
    [0] => 42000
    [1] => 1305
    [2] => FUNCTION trntv.array_agg does not exist
)
↵
Caused by: PDOException

Please advise on how to resolve

Regards,

Admin

**Comment by dbd5** [comment]
As an update - it appears the issue is caused by array_agg which happens to be a PostgreSql function used to aggregate a set of elements into an array and is not supported by MySql.

**Comment by aaiyo** [comment]
Hi thank you for the report, i've little update, hope it works :)

**Comment by dbd5** [comment]
Thanks bro!

That resolved the compatibility issue with MySql but the following errors still occur;
1. Selecting a category still throws this error;

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''1')))' at line 1
The SQL being executed was: SELECT COUNT(*) FROM `blog_post` LEFT JOIN `user` ON `blog_post`.`author_id` = `user`.`id` WHERE (`blog_post`.isdel=0) AND ((false) OR (`blog_post`.id = ANY ('1')))
Error Info: Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''1')))' at line 1
1. Searching our Posts still throws the following error;

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''{}'))))))' at line 1
The SQL being executed was: SELECT COUNT(*) FROM `blog_post` LEFT JOIN `user` ON `blog_post`.`author_id` = `user`.`id` WHERE (`blog_post`.isdel=0) AND ((lower(title) like '%gyy%') OR ((lower(description) like '%gyy%') OR ((lower(tags) like '%gyy%') OR ((lower(content) like '%gyy%') OR (`blog_post`.id = ANY ('{}'))))))
Error Info: Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''{}'))))))' at line 1

Could you take a look at the ANY clause syntax?

Regards,

Adam

**Comment by aaiyo** [comment]
Hi Adam, thanks again for your report. I haven't check it in mysql db, i did little trick in my latest update. If you don't mind, please notify me whether it work or not.

Best regards

**Comment by dbd5** [comment]
Hello Aaiyo,

Yes, I can confirm that it works in MySql.

I think the last 2 errors I pointed out in my last post are not MySql
errors, I believe they are syntax errors from the use of the ANY clause in
the SQL script for search

Regards,

Adam

**Comment by dbd5** [comment]
I believe these are resolved now, will let you know if I find any other issues

Adam

**Comment by dbd5** [comment]
Hello Aaiyo,

It appears there is still a small bug somewhere in the search criteria.

The blog Category filter doesn't work

For example, when looking at "localhost/blog/post/view?id=20", if you select a category like "localhost/blog/post/index?category=Technology", it will not find any records.

I checked, the table blog_cat_pos and it seems to provide the necessary references to join blog_post and blog_category entries.

Regards,

Adam

**Comment by aaiyo** [comment]
haha you're right, it's my stupid mistake i've push the revision :)

**Comment by dbd5** [comment]
Hi Aaiyo,

It works great now!

This really is first class work IMHO, thanks for your efforts

Regards,

Adam
