### ISSUE TITLE
Did not migrations run

### ISSUE THREAD

**Issue by sonrac** [amilna/blog#4]
After installation I'm tried migrate tables into database:
./yii migrate --migrationPath=@amilna/blog/migration
but have error "No such file or directory".
Used Yii-starter-kit with 4 domains (run from common/console)

**Comment by dbd5** [comment]
Could you check that you have it installed correctly?
If you used composer, you should have a folder \vendor\amilna at the same level as \console.

In trntv/yii2-starter-kit, \common and \console are at the same directory level as \vendor\amilna and shouldn't be a problem even with a 4 domain setup.

Suggest  you look into why your console is a level above under common.

**Comment by aaiyo** [comment]
@sonrac you should try run it from your apps root. (wherever yii file is placed).
