### ISSUE TITLE
Error extending Post model

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#5]
Hi,

I defined this

<?php
namespace common\models\blog;
use amilna\blog\models\Post as BasePost;
use Yii;
class Post extends BasePost
{
    public function new_funct()
    {
     ...
    }
}

And then added a modelmap in my config under blog as follows (I assume the method discussed here https://github.com/dektrium/yii2-user/blob/master/docs/overriding-models.md can be applied to extend any models?);

```
'modules' => [
    'blog' => [
        'class' => 'amilna\blog\Module',
        'userClass' => 'common\models\User',
        'modelMap' => [
            'Post' => 'common\models\blog\Post',
        ],
    ], 
  ....
```

I get the following errors;

Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: amilna\blog\Module::modelMap

I know this is not core to your module but I will appreciate any help, I will want to extend the post model without changing your core code

Regards,

Adam

**Comment by aaiyo** [comment]
hi i'm sorry for late reply.. (i didn't notice therer is unread message). Practically is use as this example https://github.com/amilna/iyo/blob/master/models/StaticPage.php to extend a model in blog module that used in another module.

**Comment by dbd5** [comment]
Thanks
