### ISSUE TITLE
Suggested Enhancement - Move configuration options to Yii app config files

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#6]
Hi Aaiyo,

Might I suggest this enhancement when you find some time, I think it will be useful.

Currently if you want to change the location for file uploads by KCFINDER, you have to go to \amilna\blog\Module.php and change $uploadDir = '@webroot/upload' as well as $uploadURL = '@web/upload' to whatever is prefered;

Both of these variables are public, would you consider enabling their initialization in the modules section of the standard Yii app config files (main.php) that way, there will be no need to make any changes in the module that will potentially be overwritten when you push an update?

Regards,

Adam

**Comment by aaiyo** [comment]
Hi Adam,

to change in yii app config files (main.php), just add uploadDir and uploadURL as like bellow example :

```
'blog' => [
            'class' => 'amilna\blog\Module',
            'userClass' =>  'dektrium\user\models\User',//'common\models\User',                        
            'uploadDir'=>'@app/../backend/web/static',
            'uploadURL'=>$params["backendURL"].'/static',
        ], 
```

**Comment by dbd5** [comment]
Hi Aaiyo,

Yes I did try like that because I know the variables are public but it appears that any change made in Yii config files is overwritten when the module is initiated

Regards,

A

**Comment by aaiyo** [comment]
have you check another config files? (common/config/main-local.php, backend/config/main.php, backend/config/main-local.php, frontend/config/main.php, frontend/config/main-local.php)

**Comment by anushkanz** [comment]
Hi
Thanks for this module, But image upload is not working,
When i click that button nothing happens
Thanks

**Comment by aaiyo** [comment]
Hi it should be related to javascript things could you please help me with some debug information from browser (you can use developer tools in mozilla)
Pada tanggal 24 Jan 2016 4.26 AM, anushkanz notifications@github.com menulis:Hi
Thanks for this module, But image upload is not working,
When i click that button nothing happens
Thanks

**Comment by anushkanz** [comment]
jQuery("#file-status").bootstrapSwitch(bootstrapSwitch_29bf9f81);
this is the error i got

**Comment by anushkanz** [comment]
Same time, Tags not loadings

**Comment by aaiyo** [comment]
this module is depend on boostrap.js, make sure bootstrap.js already configured properly in your layout themes
