### ISSUE TITLE
Suggested Enhancement - Support Top Authors in blog/post/view 

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#7]
Hi Aaiyo,

I have made this simple query to show top authors in blog/post/view;

```
            <?php use yii\db\Query; ?>

            <h4><?= Yii::t("app","Top Authors")?></h4>
            <ul class="nav nav-pills nav-stacked">
                <?php
                $query = new Query;
                $query->select(['author_id', 'username', 'COUNT(*) AS cnt'])
                    ->from('blog_post')
                    ->innerJoin('user', 'blog_post.author_id = user.id')
                    ->where('status = 1')
                    ->andwhere('isdel = 0')
                    ->orderBy('cnt DESC')
                    ->groupBy('author_id')
                    ->limit(4);

                $command = $query->createCommand();
                $rows = $command->queryAll();
                foreach ($rows as $r)
                {
                    echo '<li>'.Html::a($r['username'] . ' (' . $r['cnt'] . ')',["//blog/post/index","authorName"=>$r['username']]).'</li>';
                }
                ?>
            </ul>
```

Would you mind updating PostController / ActionIndex to support the following type of PostSearch;
http://localhost/blog/post/index?authorName=John+Doe

Regards,

Adam

**Comment by dbd5** [comment]
Hi Aaiyo,

I've made the following changes to PostController / ActionIndex 
1. Add $authorName = false to method signature
2. Modify the queryParams by adding the following statement;
   if ($authorName) { $req[basename(str_replace("\","/",get_class($searchModel)))]["authorName"] = $authorName;}

It works and gets the required result, but if you don't support the changes, they will be overwritten when you push the next update

Regards,

Adam

**Comment by aaiyo** [comment]
Hi Adam,

Current PostSearch model already accomodate such query. To search post by author name just put PostSearch[authorName]=.. . for example: http://localhost/blog/post/index?PostSearch[authorName]=John+Doe

I it okay?

**Comment by dbd5** [comment]
Oh yes, true - perfect! Sorry for the oversight

Adam
