### ISSUE TITLE
list of categories associated to a particular blog_post

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#8]
Hi Aaiyo,

When you are iterating through blog_posts, what is the recommended way to get the list of categories associated to a particular blog_post?

Regards,

Adam

**Comment by aaiyo** [comment]
This example how te get related category of the post

```
<h4><?= Yii::t("app","Related Categories of This Post")?></h4>
<ul class="nav nav-pills">
<?php
    foreach ($model->blogCatPos as $m)
    {                   
        echo '<li>'.Html::a($m->category->title,["//blog/post/index","category"=>$m->category->title]).'</li>';
    }       
?>          
</ul>
```

**Comment by dbd5** [comment]
Thank you so much, I'm still trying to figure out the relationship between the models re $model->blogCatPos

Regards,

Adam
