### ISSUE TITLE
Scroll pager

### ISSUE THREAD

**Issue by dbd5** [amilna/blog#9]
Dear Aaiyo,

This is just a quick question to get clarification.
Is the scroll pager at the bottom of the blog posts page activated to fetch more automatically as you scroll down or it can only fetch more when you click it?

Thanks in advance!

Adam

**Comment by aaiyo** [comment]
yes it should be fetch more when you scroll down, but i just notice that it still buggy, so i think it would be better to use default yii pager

**Comment by dbd5** [comment]
I agree, did just that
